name: build
on: [push]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Activate Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pandoc
          environment-file: environment.yml

      - name: Install Python pandoc 
        run: python setup.py install

      - name: Test Python pandoc
        run: python test.py

      - name: Build documentation
        if: matrix.os == 'ubuntu-20.04'
        run: mkdocs build

      - name: Prepare deployment
        if: matrix.os == 'ubuntu-20.04'
        run: rm .gitignore

      - name: Deploy documentation
        if: matrix.os == 'ubuntu-20.04'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "docs"
          SINGLE_COMMIT: true
          PRESERVE: true
